# Generated by Django 2.2.7 on 2019-11-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_code', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('audience', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('title_eng', models.CharField(max_length=50)),
                ('open_date', models.CharField(max_length=100)),
                ('genre1', models.CharField(max_length=30)),
                ('genre2', models.CharField(blank=True, max_length=30)),
                ('genre3', models.CharField(blank=True, max_length=30)),
                ('watch_grade', models.CharField(max_length=50)),
                ('poster_url', models.CharField(max_length=200)),
                ('user_rating', models.IntegerField()),
                ('naver_link', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
